# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'OublieTrouve' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  inherit! :search_paths
    pod 'Bean-iOS-OSX-SDK', '~> 2.1.0'

  # Pods for OublieTrouve

end
